### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by cooljeanius** [cooljeanius/MacPorts-fork#3]
CI systems are having trouble locating a working Objective-C runtime.

**Comment by cooljeanius** [comment]
Specifically, the failing configure test is failing to find `<objc/objc-api.h>`... anyone know what package that's supposed to be in?

**Comment by cooljeanius** [comment]
> Specifically, the failing configure test is failing to find `<objc/objc-api.h>`... anyone know what package that's supposed to be in?

Apparently it's from an old version of gcc, but idk if the version in question (forget which specifically atm) can actually be installed on the CI runners currently being used...

**Comment by pinskia** [comment]
objc/objc-api.h was removed in GCC 4.7.0 (https://gcc.gnu.org/r0-109347-g80e4b9e501e4e7).

**Comment by pinskia** [comment]
it should be searching for objc/runtime.h instead which is the "modern" runtime header. Note when I say modern, I mean objc1 modern rather than objc2 modern.

**Comment by cooljeanius** [comment]
ok so I didn't actually mean to close this in a045727, but, it did in fact "fix" (i.e. hack around) it anyways, so, no harm no foul...
